version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sfn-athena-results"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r0ld83lev51q"
s3_prefix = "sfn-athena-results"
region = "us-east-1"
profile = "cremich.AWSAdministratorAccess"
capabilities = "CAPABILITY_IAM"
image_repositories = []
